services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\LocationBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaLocationBundle.php'
